# Generated by Django 5.0.4 on 2024-04-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_registration',
            table='user_registration',
        ),
    ]
