# Generated by Django 4.1.13 on 2024-03-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='img_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
