# Generated by Django 4.1.13 on 2024-05-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
