# Generated by Django 4.1.13 on 2024-05-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producer',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('popular_in_decade', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'style',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='clothes/images')),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.producer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.style')),
            ],
            options={
                'db_table': 'clothes',
            },
        ),
    ]
