# Generated by Django 4.1.13 on 2024-04-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='mobile/images')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='mobile.type')),
            ],
            options={
                'db_table': 'mobile',
            },
        ),
    ]
